const scenarios={
  silica:{fraction:'respirable',objective:'Determinar la fracción respirable generada durante el corte de concreto. El análisis específico de sílice requeriría una técnica posterior; aquí practicarás la captación y el cálculo gravimétrico.'},
  wood:{fraction:'inhalable',objective:'Determinar la exposición personal a polvo de madera en la fracción inhalable mediante un muestreador que represente lo que entra por nariz y boca.'},
  flour:{fraction:'inhalable',objective:'Evaluar aerosol de harina en la fracción inhalable durante una tarea de manipulación y vertido de sacos.'}
};
const methods={respirable:{samplers:['aluminum','nylon'],filter:'pvc5',pump:'personal',flows:{aluminum:2.5,nylon:1.7}},inhalable:{samplers:['iom'],filter:null,pump:'personal',flows:{iom:2}},thoracic:{samplers:[],filter:null,pump:'personal',flows:{}},total:{samplers:['cassette'],filter:null,pump:'personal',flows:{cassette:2}}};
const state={step:0,mode:'guided',scenario:'silica',initialFlow:0,validSample:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function go(step){state.step=step;$$('.stage').forEach((el,i)=>el.classList.toggle('active',i===step));$$('.steps button').forEach((el,i)=>{el.classList.toggle('active',i===step);el.classList.toggle('done',i<step)});scrollTo({top:0,behavior:'smooth'});if(step===5)calculate()}
$$('.mode-switch button').forEach(b=>b.onclick=()=>{$$('.mode-switch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode});
$$('.scenario').forEach(b=>b.onclick=()=>{$$('.scenario').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.scenario=b.dataset.scenario;$('#objective').textContent=scenarios[state.scenario].objective;if(state.mode==='guided')$('#fraction').value=scenarios[state.scenario].fraction});
$$('.steps button').forEach(b=>b.onclick=()=>{const n=+b.dataset.step;if(n<=state.step)go(n)});
$$('.next').forEach((b,i)=>b.onclick=()=>next(i));
function next(i){
 if(i===0){if(!$('#fraction').value)return alert('Selecciona la fracción que corresponde al caso.');if($('#fraction').value!==scenarios[state.scenario].fraction)return alert('Revisa el objetivo: esa fracción no representa el aerosol que debemos evaluar en este caso.');go(1)}
 if(i===1){verifyAssembly()}
 if(i===2&&state.initialFlow)go(3);
 if(i===3&&state.validSample)go(4);
 if(i===4){const a=+$('#initialMass').value,b=+$('#finalMass').value,c=+$('#blankMass').value;if(!a||!b||b<=a||c<0)return alert('Revisa los datos de pesaje. El peso final debe superar al inicial.');go(5)}
}
$('#sampler').onchange=()=>{const names={iom:'IOM',aluminum:'Ciclón Al',nylon:'Ciclón nylon',cassette:'Cassette 37'};$('#samplerName').textContent=names[$('#sampler').value]||'Selector';$('#samplerVisual').classList.toggle('iom',$('#sampler').value==='iom')};
function verifyAssembly(){const f=$('#fraction').value,m=methods[f],errors=[];if(!m.samplers.includes($('#sampler').value))errors.push('El cabezal no corresponde con la fracción seleccionada.');if(m.filter&&$('#filter').value!==m.filter)errors.push('El método respirable requiere el filtro previsto por el método del caso.');if($('#pump').value!==m.pump)errors.push('Para partículas necesitas una bomba personal tipo P.');if(!$('#tubeCheck').checked)errors.push('Falta confirmar la manguera sin dobleces.');const box=$('#assemblyFeedback');box.hidden=false;if(errors.length){box.className='feedback error';box.innerHTML='<b>Montaje no válido</b><br>'+errors.join('<br>');return}box.className='feedback success';box.innerHTML='<b>Tren correctamente armado.</b> Calibra siempre con el cabezal y el filtro instalados.';const flow=m.flows[$('#sampler').value];$('#targetFlow').value=flow;$('#finalFlow').value=(flow-.01).toFixed(2);$('#pumpFlow').textContent=flow.toFixed(2);setTimeout(()=>go(2),650)}
$('#calibrateBtn').onclick=()=>{const expected=methods[$('#fraction').value].flows[$('#sampler').value],target=+$('#targetFlow').value;if(Math.abs(target-expected)>.05)return alert(`El caudal requerido para este selector es ${expected.toFixed(1)} L/min.`);const count=+$('#readingCount').value,vals=[];for(let i=0;i<count;i++)vals.push(target+(Math.random()-.5)*.024);let n=0;$('#readings').innerHTML='';$('#calState').textContent='Midiendo…';const timer=setInterval(()=>{const val=vals[n];$('#calReading').textContent=val.toFixed(3);$('#readings').insertAdjacentHTML('beforeend',`<span>${n+1}: ${val.toFixed(3)}</span>`);n++;if(n===count){clearInterval(timer);state.initialFlow=vals.reduce((a,b)=>a+b,0)/count;$('#calReading').textContent=state.initialFlow.toFixed(3);$('#calState').textContent='Promedio estable';$('.stage[data-stage="2"] .next').disabled=false}},160)};
$('#sampleBtn').onclick=()=>{const q0=state.initialFlow,qf=+$('#finalFlow').value,t=+$('#duration').value,diff=Math.abs(qf-q0);const errors=[];if(!$('#zoneCheck').checked)errors.push('El cabezal no está confirmado en la zona respiratoria.');if($('#fraction').value==='respirable'&&!$('#uprightCheck').checked)errors.push('El ciclón debe mantenerse vertical.');if(t<45||t>480)errors.push('La duración debe estar entre 45 y 480 minutos para este ejercicio.');if(diff>Math.max(.1,q0*.05))errors.push('La diferencia entre caudal inicial y final invalida la muestra.');const box=$('#sampleFeedback');box.hidden=false;if(errors.length){state.validSample=false;box.className='feedback error';box.innerHTML='<b>Muestra no válida</b><br>'+errors.join('<br>');return}state.validSample=true;box.className='feedback success';box.innerHTML='<b>Muestreo completado.</b> El caudal se mantuvo dentro del criterio de aceptación.';$('.stage[data-stage="3"] .next').disabled=false};
['initialMass','finalMass'].forEach(id=>$('#'+id).oninput=()=>$('#balanceValue').textContent=(+$('#'+id).value).toFixed(3));
function calculate(){const qi=state.initialFlow,qf=+$('#finalFlow').value,q=(qi+qf)/2,t=+$('#duration').value,V=q*t/1000,net=(+$('#finalMass').value-+$('#initialMass').value)-+$('#blankMass').value,C=net/V,diff=Math.abs(qf-qi)/qi*100;$('#concentration').textContent=C.toFixed(2);$('#netMass').textContent=net.toFixed(3)+' mg';$('#volume').textContent=V.toFixed(3)+' m³';$('#flowDiff').textContent=diff.toFixed(2)+' %';$('#validity').textContent=state.validSample?'Válida':'Revisar';$('#resultMeaning').textContent='Resultado correspondiente a la fracción '+$('#fraction').selectedOptions[0].text.toLowerCase()+'. Para identificar un compuesto específico se necesita el análisis químico correspondiente.'}
$('#restartBtn').onclick=()=>location.reload();$('#printBtn').onclick=()=>print();$('#helpBtn').onclick=()=>$('#helpDialog').showModal();$$('.dialog-close').forEach(b=>b.onclick=()=>$('#helpDialog').close());
