const scenarios={
  silica:{fraction:'respirable',objective:'Determinar la fracción respirable generada durante el corte de concreto. El análisis específico de sílice requeriría una técnica posterior; aquí practicarás la captación y el cálculo gravimétrico.'},
  wood:{fraction:'inhalable',objective:'Determinar la exposición personal a polvo de madera en la fracción inhalable mediante un muestreador que represente lo que entra por nariz y boca.'},
  flour:{fraction:'inhalable',objective:'Evaluar aerosol de harina en la fracción inhalable durante una tarea de manipulación y vertido de sacos.'},
  caustic:{fraction:'alkaline',objective:'Evaluar la niebla o aerosol alcalino generado al rociar, agitar o aplicar a presión una solución de soda cáustica. El NaOH no es un gas ni un vapor; se capta en un filtro y se determina mediante el método de polvos alcalinos.'}
};
const methods={respirable:{samplers:['aluminum','nylon'],filter:'pvc5',pump:'personal',flows:{aluminum:2.5,nylon:1.7}},inhalable:{samplers:['iom'],filter:null,pump:'personal',flows:{iom:2}},thoracic:{samplers:[],filter:null,pump:'personal',flows:{}},alkaline:{samplers:['ptfe'],filter:'ptfe1',pump:'personal',flows:{ptfe:2}}};
const state={step:0,mode:'guided',scenario:'silica',initialFlow:0,validSample:false};
const SUPABASE_URL='https://lfdmbkzghnwvsapxypvt.supabase.co';
const SUPABASE_KEY='sb_publishable_bRnkA6PA8-v073nrw9zxiQ_8rVGiOn1';
const ACCESS_SESSION_KEY='movida-sst-aerosoles-session';
const ACCESS_ATTEMPTS_KEY='movida-sst-aerosoles-attempts';
const TUTORIAL_SEEN_KEY='movida-sst-aerosoles-tutorial-v1';
const ACCESS_DURATION=20*60*1000, BLOCK_DURATION=15*60*1000, MAX_ATTEMPTS=5;
let tutorialIndex=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const guidedCopy=[
  ['Define qué debes captar','Selecciona el escenario y luego confirma la fracción o el método recomendado.','Usar selección recomendada'],
  ['Arma un tren compatible','El selector, el filtro, la bomba y la manguera deben corresponder al método elegido.','Preparar tren correcto'],
  ['Calibra el tren completo','Comprueba el caudal objetivo con el cabezal, filtro y manguera ya instalados.','Preparar calibración'],
  ['Controla la muestra personal','Confirma la zona respiratoria, la orientación del ciclón cuando aplique y el caudal final.','Preparar muestreo'],
  ['Revisa el análisis del laboratorio','Para aerosoles gravimétricos se pesan filtros; para NaOH se determina alcalinidad químicamente.','Revisar datos sugeridos'],
  ['Interpreta, no solo calcules','Comprueba masa corregida, volumen, variación del caudal y alcance analítico del resultado.',null]
];
const learningCopy=[
 ['Planificación del muestreo','Es la definición previa del agente, la tarea, la población y el objetivo de medición.','Evita escoger un cabezal, filtro o caudal que no respondan al riesgo evaluado.','La fracción o el método debe coincidir con el criterio de comparación y el análisis del laboratorio.'],
 ['Tren de muestreo','Es el conjunto formado por selector, medio de captación, manguera y bomba.','Hace que solo llegue al filtro el aerosol definido por el método y mantiene el caudal requerido.','Un montaje incompatible produce una muestra que no representa la exposición buscada.'],
 ['Calibración de caudal','Es la comprobación del flujo a través del tren completo antes de muestrear.','Permite conocer el volumen real de aire que atravesará el filtro.','Las lecturas deben ser estables y corresponder al caudal especificado para el selector.'],
 ['Muestreo personal','Es la captación del aerosol dentro de la zona respiratoria durante una tarea representativa.','Relaciona la masa captada con la exposición real del trabajador y el tiempo observado.','La ubicación, duración, orientación y estabilidad del caudal determinan la validez de la muestra.'],
 ['Análisis de laboratorio','Es la determinación de la masa o del analito captado, con corrección mediante blancos.','Convierte el material retenido en un dato cuantificable y trazable.','La gravimetría informa masa de aerosol; NIOSH 7401 informa alcalinidad como NaOH equivalente.'],
 ['Resultado e interpretación','Es la concentración calculada al dividir la masa corregida entre el volumen de aire.','Permite comparar una exposición con el criterio aplicable y decidir acciones preventivas.','Un valor en mg/m³ solo es válido para la fracción, agente, periodo y método que originaron la muestra.']
];
function applyGuidedDefaults(step=state.step){const fraction=scenarios[state.scenario].fraction,method=methods[fraction];if(step===0)$('#fraction').value=fraction;if(step===1){$('#sampler').value=method.samplers[0]||'';$('#filter').value=method.filter||($('#filter').value||'pvc5');$('#pump').value=method.pump;$('#tubeCheck').checked=true;$('#sampler').dispatchEvent(new Event('change'))}if(step===2){const sampler=$('#sampler').value||method.samplers[0],flow=method.flows[sampler];if(flow){$('#targetFlow').value=flow;$('#readingCount').value='10'}}if(step===3){$('#zoneCheck').checked=true;$('#uprightCheck').checked=fraction==='respirable';if(state.initialFlow)$('#finalFlow').value=(state.initialFlow-.01).toFixed(2)}updateGuide()}
function updateGuide(){const dashboard=$('#guideDashboard');dashboard.hidden=state.mode!=='guided';if(dashboard.hidden)return;const [title,text,action]=guidedCopy[state.step],learn=learningCopy[state.step],percent=Math.round(state.step/5*100);$('#guideStep').textContent=`PASO ${state.step+1} DE 6`;$('#guidePercent').textContent=`${percent}%`;$('#guideProgress').style.width=`${percent}%`;$('.guide-progress').setAttribute('aria-valuenow',percent);$('#guideTitle').textContent=title;$('#guideText').textContent=text;$('#guideAction').textContent=action||'Revisar resultado';$('#guideAction').onclick=()=>{applyGuidedDefaults(state.step);$(`.stage[data-stage="${state.step}"]`).scrollIntoView({behavior:'smooth',block:'start'})};$$('#guideChecklist li').forEach((li,i)=>{li.classList.toggle('done',i<state.step);li.classList.toggle('current',i===state.step)});$('#learningTopic').textContent=learn[0];$('#learningWhat').textContent=learn[1];$('#learningPurpose').textContent=learn[2];$('#learningInterpret').textContent=learn[3]}
function go(step){state.step=step;$$('.stage').forEach((el,i)=>el.classList.toggle('active',i===step));$$('.steps button').forEach((el,i)=>{el.classList.toggle('active',i===step);el.classList.toggle('done',i<step)});updateGuide();scrollTo({top:0,behavior:'smooth'});if(step===5)calculate()}
$$('.mode-switch button').forEach(b=>b.onclick=()=>{$$('.mode-switch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;if(state.mode==='guided')applyGuidedDefaults();else updateGuide()});
$$('.scenario').forEach(b=>b.onclick=()=>{$$('.scenario').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.scenario=b.dataset.scenario;$('#objective').textContent=scenarios[state.scenario].objective;if(state.mode==='guided')applyGuidedDefaults(0);updateLabMode()});
$$('.steps button').forEach(b=>b.onclick=()=>{const n=+b.dataset.step;if(n<=state.step)go(n)});
$$('.next').forEach((b,i)=>b.onclick=()=>next(i));
function next(i){
 if(i===0){if(!$('#fraction').value)return alert('Selecciona la fracción que corresponde al caso.');if($('#fraction').value!==scenarios[state.scenario].fraction)return alert('Revisa el objetivo: esa fracción no representa el aerosol que debemos evaluar en este caso.');go(1)}
 if(i===1){verifyAssembly()}
 if(i===2&&state.initialFlow)go(3);
 if(i===3&&state.validSample)go(4);
 if(i===4){if(state.scenario==='caustic'){const s=+$('#sampleNaohMass').value,b=+$('#blankNaohMass').value;if(s<=0||b<0||s<=b)return alert('Revisa el resultado del laboratorio: la muestra debe superar al blanco.')}else{const a=+$('#initialMass').value,b=+$('#finalMass').value,c=+$('#blankMass').value;if(!a||!b||b<=a||c<0)return alert('Revisa los datos de pesaje. El peso final debe superar al inicial.')}go(5)}
}
$('#sampler').onchange=()=>{const names={iom:'IOM',aluminum:'Ciclón Al',nylon:'Ciclón nylon',ptfe:'PTFE NaOH'};$('#samplerName').textContent=names[$('#sampler').value]||'Selector';$('#samplerVisual').classList.toggle('iom',$('#sampler').value==='iom')};
function updateLabMode(){const caustic=state.scenario==='caustic';$('#gravimetricLab').hidden=caustic;$('#causticLab').hidden=!caustic;$('#labExplanation').innerHTML=caustic?'<b>Análisis químico de alcalinidad</b><p>El laboratorio extrae el filtro y determina la alcalinidad total, expresada como NaOH equivalente. No se calcula por diferencia de peso del filtro.</p>':'<b>Control gravimétrico</b><p>Los filtros y blancos se acondicionan en la misma sala; se controla temperatura, humedad y electricidad estática antes del pesaje.</p>'}
function verifyAssembly(){const f=$('#fraction').value,m=methods[f],errors=[];if(!m.samplers.includes($('#sampler').value))errors.push('El cabezal no corresponde con la fracción o método seleccionado.');if(m.filter&&$('#filter').value!==m.filter)errors.push('El medio de captación no corresponde con el método del caso.');if($('#pump').value!==m.pump)errors.push('Para partículas necesitas una bomba personal tipo P.');if(!$('#tubeCheck').checked)errors.push('Falta confirmar la manguera sin dobleces.');const box=$('#assemblyFeedback');box.hidden=false;if(errors.length){box.className='feedback error';box.innerHTML='<b>Montaje no válido</b><br>'+errors.join('<br>');return}box.className='feedback success';box.innerHTML='<b>Tren correctamente armado.</b> Calibra siempre con el cabezal y el filtro instalados.';const flow=m.flows[$('#sampler').value];$('#targetFlow').value=flow;$('#finalFlow').value=(flow-.01).toFixed(2);$('#pumpFlow').textContent=flow.toFixed(2);setTimeout(()=>go(2),650)}
$('#calibrateBtn').onclick=()=>{const expected=methods[$('#fraction').value].flows[$('#sampler').value],target=+$('#targetFlow').value;if(Math.abs(target-expected)>.05)return alert(`El caudal requerido para este selector es ${expected.toFixed(1)} L/min.`);const count=+$('#readingCount').value,vals=[];for(let i=0;i<count;i++)vals.push(target+(Math.random()-.5)*.024);let n=0;$('#readings').innerHTML='';$('#calState').textContent='Midiendo…';const timer=setInterval(()=>{const val=vals[n];$('#calReading').textContent=val.toFixed(3);$('#readings').insertAdjacentHTML('beforeend',`<span>${n+1}: ${val.toFixed(3)}</span>`);n++;if(n===count){clearInterval(timer);state.initialFlow=vals.reduce((a,b)=>a+b,0)/count;$('#calReading').textContent=state.initialFlow.toFixed(3);$('#calState').textContent='Promedio estable';$('.stage[data-stage="2"] .next').disabled=false}},160)};
$('#sampleBtn').onclick=()=>{const q0=state.initialFlow,qf=+$('#finalFlow').value,t=+$('#duration').value,diff=Math.abs(qf-q0);const errors=[];if(!$('#zoneCheck').checked)errors.push('El cabezal no está confirmado en la zona respiratoria.');if($('#fraction').value==='respirable'&&!$('#uprightCheck').checked)errors.push('El ciclón debe mantenerse vertical.');if(t<45||t>480)errors.push('La duración debe estar entre 45 y 480 minutos para este ejercicio.');if(diff>Math.max(.1,q0*.05))errors.push('La diferencia entre caudal inicial y final invalida la muestra.');const box=$('#sampleFeedback');box.hidden=false;if(errors.length){state.validSample=false;box.className='feedback error';box.innerHTML='<b>Muestra no válida</b><br>'+errors.join('<br>');return}state.validSample=true;box.className='feedback success';box.innerHTML='<b>Muestreo completado.</b> El caudal se mantuvo dentro del criterio de aceptación.';$('.stage[data-stage="3"] .next').disabled=false};
['initialMass','finalMass'].forEach(id=>$('#'+id).oninput=()=>$('#balanceValue').textContent=(+$('#'+id).value).toFixed(3));
function calculate(){const qi=state.initialFlow,qf=+$('#finalFlow').value,q=(qi+qf)/2,t=+$('#duration').value,V=q*t/1000,caustic=state.scenario==='caustic',net=caustic?(+$('#sampleNaohMass').value-+$('#blankNaohMass').value):((+$('#finalMass').value-+$('#initialMass').value)-+$('#blankMass').value),C=net/V,diff=Math.abs(qf-qi)/qi*100;$('#concentration').textContent=C.toFixed(2);$('#netMass').textContent=net.toFixed(3)+' mg';$('#volume').textContent=V.toFixed(3)+' m³';$('#flowDiff').textContent=diff.toFixed(2)+' %';$('#validity').textContent=state.validSample?'Válida':'Revisar';$('#resultMeaning').textContent=caustic?'Resultado de niebla alcalina expresado como NaOH equivalente. Corresponde a gotículas captadas y analizadas químicamente; no a gas ni vapor.':'Resultado correspondiente a la fracción '+$('#fraction').selectedOptions[0].text.toLowerCase()+'. Para identificar un compuesto específico se necesita el análisis químico correspondiente.';$('#resultFormula').textContent=caustic?'C = (NaOH muestra − NaOH blanco) / V':'C = [(Pf − Pi) − B] / V';$('#formulaMeaning').textContent=caustic?'El laboratorio determina la alcalinidad total del extracto y la expresa como masa equivalente de NaOH. Otros compuestos alcalinos pueden interferir.':'Una concentración gravimétrica indica masa de aerosol por volumen de aire. No identifica por sí sola la composición química del polvo.'}
$('#restartBtn').onclick=()=>location.reload();$('#printBtn').onclick=()=>print();$('#helpBtn').onclick=()=>$('#helpDialog').showModal();$$('.dialog-close').forEach(b=>b.onclick=()=>$('#helpDialog').close());

function readJson(storage,key,fallback){try{return JSON.parse(storage.getItem(key)||'null')||fallback}catch{return fallback}}
function writeJson(storage,key,value){try{storage.setItem(key,JSON.stringify(value))}catch{}}
function setLoginMessage(message,type='error'){const el=$('#loginMessage');el.textContent=message;el.classList.toggle('success',type==='success')}
function getAttempts(){const value=readJson(localStorage,ACCESS_ATTEMPTS_KEY,{count:0,blockedUntil:0});if(value.blockedUntil&&value.blockedUntil<=Date.now()){localStorage.removeItem(ACCESS_ATTEMPTS_KEY);return{count:0,blockedUntil:0}}return value}
function blockMessage(until){const min=Math.max(1,Math.ceil((until-Date.now())/60000));return`Demasiados intentos. Espera ${min} ${min===1?'minuto':'minutos'} antes de volver a intentar.`}
function failedAttempt(){const current=getAttempts(),count=(current.count||0)+1;if(count>=MAX_ATTEMPTS){const blockedUntil=Date.now()+BLOCK_DURATION;writeJson(localStorage,ACCESS_ATTEMPTS_KEY,{count:0,blockedUntil});return blockMessage(blockedUntil)}writeJson(localStorage,ACCESS_ATTEMPTS_KEY,{count,blockedUntil:0});const remaining=MAX_ATTEMPTS-count;return`No pudimos validar esos datos. Revisa la cédula y la clave. Te ${remaining===1?'queda 1 intento':`quedan ${remaining} intentos`}.`}
function openAccess(member,persist=true){const name=[member?.nombres,member?.apellidos].filter(Boolean).join(' ').trim()||member?.name||'integrante';const expiresAt=member?.expiresAt||Date.now()+ACCESS_DURATION;if(persist)writeJson(sessionStorage,ACCESS_SESSION_KEY,{name,expiresAt});$('#memberName').textContent=name;$('#loginGate').hidden=true;document.body.classList.remove('auth-locked');clearTimeout(window.aerosolAccessTimer);window.aerosolAccessTimer=setTimeout(()=>closeAccess(true),Math.max(0,expiresAt-Date.now()));scrollTo(0,0);setTimeout(()=>{if(!localStorage.getItem(TUTORIAL_SEEN_KEY))openTutorial()},250)}
function closeAccess(expired=false){sessionStorage.removeItem(ACCESS_SESSION_KEY);$('#loginGate').hidden=false;document.body.classList.add('auth-locked');$('#memberLogin').reset();setLoginMessage(expired?'Tu sesión de 20 minutos finalizó. Ingresa nuevamente para continuar.':'Sesión cerrada correctamente.',expired?'error':'success');$('#memberId').focus()}
async function submitLogin(event){event.preventDefault();const cedula=$('#memberId').value.replace(/\D/g,''),codigo=$('#memberPassword').value.trim(),attempts=getAttempts();if(attempts.blockedUntil>Date.now())return setLoginMessage(blockMessage(attempts.blockedUntil));if(!cedula||!codigo)return setLoginMessage('Escribe tu cédula y tu clave para continuar.');const btn=$('#loginSubmit');btn.disabled=true;btn.querySelector('span').textContent='Verificando acceso…';setLoginMessage('', 'success');try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/acceso_integrante`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({p_cedula:cedula,p_codigo:codigo})});if(!response.ok)throw new Error(`Acceso ${response.status}`);const payload=await response.json(),member=Array.isArray(payload)?payload[0]:payload;if(!member){$('#memberPassword').value='';return setLoginMessage(failedAttempt())}localStorage.removeItem(ACCESS_ATTEMPTS_KEY);openAccess(member)}catch(error){console.error(error);setLoginMessage('El servicio de acceso no está disponible en este momento. Intenta nuevamente en unos minutos.')}finally{btn.disabled=false;btn.querySelector('span').textContent='Abrir simulador'}}
$('#memberLogin').addEventListener('submit',submitLogin);$('#logoutBtn').onclick=()=>closeAccess(false);$('#togglePassword').onclick=()=>{const input=$('#memberPassword'),show=input.type==='password';input.type=show?'text':'password';$('#togglePassword').textContent=show?'Ocultar':'Mostrar'};
const session=readJson(sessionStorage,ACCESS_SESSION_KEY,null);if(session?.expiresAt>Date.now()){openAccess(session,false)}else{sessionStorage.removeItem(ACCESS_SESSION_KEY);const attempts=getAttempts();if(attempts.blockedUntil>Date.now())setLoginMessage(blockMessage(attempts.blockedUntil));$('#memberId').focus()}
$('#manualSearch').addEventListener('input',event=>{const query=event.target.value.trim().toLocaleLowerCase('es');let found=0;$$('.function-manual details').forEach(detail=>{const visible=!query||detail.textContent.toLocaleLowerCase('es').includes(query);detail.hidden=!visible;if(visible){found++;if(query)detail.open=true}});$('#manualEmpty').hidden=found>0});
$$('[data-manual-target]').forEach(button=>button.onclick=()=>{const target=$('#'+button.dataset.manualTarget);$$('.function-manual details').forEach(detail=>detail.open=false);target.hidden=false;target.open=true;target.scrollIntoView({behavior:'smooth',block:'center'})});
function renderTutorial(){$$('[data-tutorial-step]').forEach((page,index)=>page.hidden=index!==tutorialIndex);$('#tutorialCounter').textContent=`${tutorialIndex+1} de 4`;$$('.tutorial-status i').forEach((dot,index)=>dot.classList.toggle('active',index<=tutorialIndex));$('#tutorialBack').hidden=tutorialIndex===0;$('#tutorialNext').hidden=tutorialIndex===3;$('#tutorialStart').hidden=tutorialIndex!==3}
function openTutorial(){tutorialIndex=0;renderTutorial();if(!$('#tutorialDialog').open)$('#tutorialDialog').showModal()}
function closeTutorial(){localStorage.setItem(TUTORIAL_SEEN_KEY,'1');$('#tutorialDialog').close()}
$('#tutorialNext').onclick=()=>{tutorialIndex=Math.min(3,tutorialIndex+1);renderTutorial()};$('#tutorialBack').onclick=()=>{tutorialIndex=Math.max(0,tutorialIndex-1);renderTutorial()};$('#tutorialSkip').onclick=closeTutorial;$('#tutorialClose').onclick=closeTutorial;$('#tutorialStart').onclick=()=>{closeTutorial();go(0);setTimeout(()=>$('.scenario.selected').scrollIntoView({behavior:'smooth',block:'center'}),250)};$('#openTutorialBtn').onclick=()=>{$('#helpDialog').close();openTutorial()};
$('#topTutorialBtn').onclick=openTutorial;
applyGuidedDefaults(0);
